import { expect } from '@playwright/test';
export async function tap(page,selector){const l=page.locator(selector).first();await l.waitFor({state:'visible',timeout:30000});await expect(l).toBeEnabled();await expect.poll(async()=>l.evaluate(el=>{if(!(el instanceof HTMLElement)||el.matches(':disabled'))return false;const s=getComputedStyle(el),r=el.getBoundingClientRect();if(s.display==='none'||s.visibility==='hidden'||s.pointerEvents==='none'||r.width<=0||r.height<=0)return false;const x=Math.max(0,Math.min(innerWidth-1,r.left+r.width/2)),y=Math.max(0,Math.min(innerHeight-1,r.top+r.height/2));const hit=document.elementFromPoint(x,y);return hit===el||!!el.contains(hit);}),{timeout:30000,message:`${selector} must be the actual topmost touch target`}).toBe(true);await l.tap();}
export async function openOnlineEntry(page){await tap(page,'#onlineBtn');}
export async function openAutoMatch(page){await openOnlineEntry(page);await tap(page,'#openAutoMatch');}
export async function createRoomHost(page){await openOnlineEntry(page);await tap(page,'#openRoomCode');await tap(page,'#p2pHost');await expect.poll(async()=>((await page.locator('#roomCodeText').textContent())||'').trim(),{timeout:30000}).toMatch(/^[A-Z2-9]{6}$/);return ((await page.locator('#roomCodeText').textContent())||'').trim();}
export async function joinRoomGuest(page,code){await openOnlineEntry(page);await tap(page,'#openRoomCode');await tap(page,'#p2pGuest');await page.locator('#roomCodeInput').fill(code);await tap(page,'#joinRoom');}
export async function pairByRoomCode(host,guest){const code=await createRoomHost(host);await joinRoomGuest(guest,code);await Promise.all([waitForLobby(host),waitForLobby(guest)]);return code;}
export async function waitForLobby(page){await page.locator('#onlineRoomDeck').waitFor({state:'visible',timeout:60000});await expect(page.locator('#modal')).toHaveClass(/online-room-r22/);await expect(page.locator('#onlineRoomDeck .online-room-card')).not.toHaveCount(0);}
export async function selectFour(page){for(let i=0;i<4;i++){const cards=page.locator('#onlineRoomDeck .online-room-card:not(.selected)');await expect.poll(()=>cards.count()).toBeGreaterThan(0);const card=cards.first();const b=await card.boundingBox();if(!b)throw new Error('CARD_SURFACE_DETACHED');await page.touchscreen.tap(b.x+b.width/2,b.y+Math.min(30,b.height/2));await expect.poll(async()=>page.locator('#onlineRoomDeck .online-room-card.selected').count()).toBe(i+1);}}
export async function waitRemoteCount(page,count){await expect(page.locator('#roomReadyState')).toContainText(`상대 덱 ${count}/4`,{timeout:30000});}
export async function startBattle(host,guest){const startHost=host.locator('#onlineRoomStart');const startGuest=guest.locator('#onlineRoomStart');await expect.poll(async()=>((await startHost.isEnabled().catch(()=>false))||(await startGuest.isEnabled().catch(()=>false))),{timeout:30000}).toBe(true);let target=null;if(await startHost.isEnabled().catch(()=>false))target=host;else if(await startGuest.isEnabled().catch(()=>false))target=guest;else throw new Error('READY_START_BUTTON_UNAVAILABLE');await tap(target,'#onlineRoomStart');await Promise.all([waitBattle(host),waitBattle(guest)]);}
export async function waitBattle(page){await page.locator('#actions').waitFor({state:'visible',timeout:60000});await page.locator('#actionButtons').waitFor({state:'visible'});}
export async function touchFirstLegalAction(page){const buttons=page.locator('#actionButtons button:not([disabled]), #actionButtons .skillbtn:not([disabled])');await expect.poll(()=>buttons.count()).toBeGreaterThan(0);const button=buttons.first();const b=await button.boundingBox();if(!b)throw new Error('ACTION_BUTTON_DETACHED');await page.touchscreen.tap(b.x+b.width/2,b.y+b.height/2);await resolveInteraction(page);}
export async function resolveInteraction(page){for(let i=0;i<8;i++){const modal=page.locator('#modal.open');if(!(await modal.count()))return;const candidates=modal.locator('button:not([disabled]):visible');const n=await candidates.count();if(!n)return;let chosen=null;for(let j=0;j<n;j++){const t=(await candidates.nth(j).textContent()||'').trim();if(!/취소|뒤로|연결 끊기|메뉴/.test(t)){chosen=candidates.nth(j);break}}if(!chosen)return;const b=await chosen.boundingBox();if(!b)return;await page.touchscreen.tap(b.x+b.width/2,b.y+b.height/2);await page.waitForTimeout(100);}}
export async function runtimeSummary(page){return await page.evaluate(()=>({runtime:window.OnlineRuntime?.debug?.()||null,diagnostic:window.DiagnosticTraceOwner?.currentStateSummary?.()||null,dom:window.DiagnosticTraceOwner?.domSurfaceSummary?.()||null,room:document.getElementById('roomReadyState')?.textContent||null,actions:document.querySelectorAll('#actionButtons button:not([disabled])').length}));}
export async function actualPlayerPath(host,guest){const roomCode=await pairByRoomCode(host,guest);await selectFour(host);await waitRemoteCount(guest,4);await selectFour(guest);await waitRemoteCount(host,4);await startBattle(host,guest);const h=await runtimeSummary(host),g=await runtimeSummary(guest);const actorPage=h.actions>0?host:g.actions>0?guest:null;if(!actorPage)throw new Error('FIRST_ACTION_READINESS_MISSING');await touchFirstLegalAction(actorPage);return {roomCode,host:await runtimeSummary(host),guest:await runtimeSummary(guest)};}
